create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  message text not null check (char_length(message) between 1 and 500),
  image_path text,
  created_at timestamptz not null default now(),
  likes_count integer not null default 0
);

alter table public.posts add column if not exists likes_count integer not null default 0;
alter table public.posts disable row level security;
grant select, insert, update, delete on table public.posts to anon, authenticated;
grant usage, select on sequence public.posts_id_seq to anon, authenticated;

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  message text not null check (char_length(message) between 1 and 280),
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create index if not exists comments_post_created_idx
on public.comments(post_id, created_at);

alter table public.comments disable row level security;
grant select, insert, update, delete on table public.comments to anon, authenticated;
grant usage, select on sequence public.comments_id_seq to anon, authenticated;

create or replace function public.increment_post_like(target_post_id bigint)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  next_count integer;
begin
  update public.posts
  set likes_count = likes_count + 1
  where id = target_post_id
  returning likes_count into next_count;

  if next_count is null then
    raise exception 'post not found';
  end if;

  return next_count;
end;
$$;

grant execute on function public.increment_post_like(bigint) to anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'post-images',
  'post-images',
  true,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public read post images" on storage.objects;
drop policy if exists "Public upload post images" on storage.objects;
drop policy if exists "Public update post images" on storage.objects;
drop policy if exists "Public delete post images" on storage.objects;

create policy "Public read post images"
on storage.objects for select
using (bucket_id = 'post-images');

create policy "Public upload post images"
on storage.objects for insert
with check (bucket_id = 'post-images');

create policy "Public update post images"
on storage.objects for update
using (bucket_id = 'post-images')
with check (bucket_id = 'post-images');

create policy "Public delete post images"
on storage.objects for delete
using (bucket_id = 'post-images');
