create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  message text not null check (char_length(message) between 1 and 500),
  image_path text,
  created_at timestamptz not null default now()
);

alter table public.posts disable row level security;
grant select, insert, update, delete on table public.posts to anon, authenticated;
grant usage, select on sequence public.posts_id_seq to anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'post-images',
  'post-images',
  true,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public read post images" on storage.objects;
drop policy if exists "Public upload post images" on storage.objects;
drop policy if exists "Public update post images" on storage.objects;
drop policy if exists "Public delete post images" on storage.objects;

create policy "Public read post images"
on storage.objects for select
using (bucket_id = 'post-images');

create policy "Public upload post images"
on storage.objects for insert
with check (bucket_id = 'post-images');

create policy "Public update post images"
on storage.objects for update
using (bucket_id = 'post-images')
with check (bucket_id = 'post-images');

create policy "Public delete post images"
on storage.objects for delete
using (bucket_id = 'post-images');
