create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  message text not null check (char_length(message) between 1 and 500),
  image_path text,
  created_at timestamptz not null default now(),
  likes_count integer not null default 0,
  author_id uuid not null default auth.uid() references auth.users(id) on delete restrict
);

alter table public.posts add column if not exists likes_count integer not null default 0;
alter table public.posts add column if not exists author_id uuid references auth.users(id) on delete restrict;
alter table public.posts alter column author_id set default auth.uid();

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  message text not null check (char_length(message) between 1 and 280),
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  author_id uuid not null default auth.uid() references auth.users(id) on delete restrict
);

alter table public.comments add column if not exists author_id uuid references auth.users(id) on delete restrict;
alter table public.comments alter column author_id set default auth.uid();

create index if not exists comments_post_created_idx
on public.comments(post_id, created_at);

alter table public.posts enable row level security;
alter table public.comments enable row level security;

revoke insert, update, delete on public.posts from anon;
revoke insert, update, delete on public.comments from anon;
grant select on public.posts to anon, authenticated;
grant select, insert, update, delete on public.posts to authenticated;
grant select on public.comments to anon, authenticated;
grant select, insert, update, delete on public.comments to authenticated;
grant usage, select on sequence public.posts_id_seq to authenticated;
grant usage, select on sequence public.comments_id_seq to authenticated;

drop policy if exists "posts_public_read" on public.posts;
drop policy if exists "posts_owner_insert" on public.posts;
drop policy if exists "posts_owner_update" on public.posts;
drop policy if exists "posts_owner_delete" on public.posts;

create policy "posts_public_read"
on public.posts for select to anon, authenticated using (true);

create policy "posts_owner_insert"
on public.posts for insert to authenticated
with check (auth.uid() = author_id);

create policy "posts_owner_update"
on public.posts for update to authenticated
using (auth.uid() = author_id)
with check (auth.uid() = author_id);

create policy "posts_owner_delete"
on public.posts for delete to authenticated
using (auth.uid() = author_id);

drop policy if exists "comments_public_read" on public.comments;
drop policy if exists "comments_owner_insert" on public.comments;
drop policy if exists "comments_owner_update" on public.comments;
drop policy if exists "comments_owner_delete" on public.comments;

create policy "comments_public_read"
on public.comments for select to anon, authenticated using (true);

create policy "comments_owner_insert"
on public.comments for insert to authenticated
with check (auth.uid() = author_id);

create policy "comments_owner_update"
on public.comments for update to authenticated
using (auth.uid() = author_id)
with check (auth.uid() = author_id);

create policy "comments_owner_delete"
on public.comments for delete to authenticated
using (auth.uid() = author_id);

create or replace function public.increment_post_like(target_post_id bigint)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  next_count integer;
begin
  update public.posts
  set likes_count = likes_count + 1
  where id = target_post_id
  returning likes_count into next_count;

  if next_count is null then
    raise exception 'post not found';
  end if;

  return next_count;
end;
$$;

grant execute on function public.increment_post_like(bigint) to anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'post-images',
  'post-images',
  true,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "post_images_public_read" on storage.objects;
drop policy if exists "post_images_owner_insert" on storage.objects;
drop policy if exists "post_images_owner_update" on storage.objects;
drop policy if exists "post_images_owner_delete" on storage.objects;
drop policy if exists "Public read post images" on storage.objects;
drop policy if exists "Public upload post images" on storage.objects;
drop policy if exists "Public update post images" on storage.objects;
drop policy if exists "Public delete post images" on storage.objects;

create policy "post_images_public_read"
on storage.objects for select to anon, authenticated
using (bucket_id = 'post-images');

create policy "post_images_owner_insert"
on storage.objects for insert to authenticated
with check (bucket_id = 'post-images' and owner_id = auth.uid()::text);

create policy "post_images_owner_update"
on storage.objects for update to authenticated
using (bucket_id = 'post-images' and owner_id = auth.uid()::text)
with check (bucket_id = 'post-images' and owner_id = auth.uid()::text);

create policy "post_images_owner_delete"
on storage.objects for delete to authenticated
using (bucket_id = 'post-images' and owner_id = auth.uid()::text);
